name: CI/CD workflow

env:
  SERVER_IP: "141.94.79.103"
  SERVER_USER: root

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout le code
        uses: actions/checkout@v4
      - name: déployer sur le serveur
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< "${{ secrets.SSK_KEY_VPS }}"
          mkdir -p ~/.ssh
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          ssh $SERVER_USER@$SERVER_IP 'mkdir -p /var/www/cv'
          scp -r index.html img css $SERVER_USER@SERVER_IP:/var/www/cv/