name: CI/CD workflow

env:
  SERVER_IP: '141.94.79.103'
  SERVER_USER: 'omeruis'

# Paramètres pour gérer la concurrence des jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # Groupe de concurrence basé sur le nom du workflow et la référence git
  cancel-in-progress: true # Annule les jobs en cours si un nouveau job est lancé dans le même groupe

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout le code
        uses: actions/checkout@v4
      - name: déployer sur le serveur
        run: |
          ping -c 4 ${{ secrets.SERVER_IP }}
          nc -zv ${{ secrets.SERVER_IP }} 22
          eval $(ssh-agent -s)
          ssh-add - <<< "${{ secrets.SSH_KEY_VPS }}"
          mkdir -p ~/.ssh
          ssh-keyscan -H 141.94.79.103 >> ~/.ssh/known_hosts
          ssh $SERVER_USER@$141.94.79.103 'mkdir -p /var/www/html/cv'
          scp -r index.html img css $SERVER_USER@141.94.79.103:/var/www/html/cv/